### ISSUE TITLE
Code Don't start up 

### ISSUE THREAD

**Issue by xeron56** [navoshta/behavioral-cloning#3]
![dwqd](https://user-images.githubusercontent.com/11449967/35838575-203cddc4-0b16-11e8-870e-e9bffbc9f4ce.PNG)

Can u write about how to start up your code fully in anaconda ...

**Comment by alexstaravoitau** [comment]
Hi @shahidul56 — I looked into that a while ago to be honest, any chance there has been some changes in TensorFlow APIs since then? The version I used back then was pre-1.0 I think.

Also, feel free to submit a PR if you get to the bottom of this!

**Comment by xeron56** [comment]
Can u please upload all name of dependency with their appropriate version. It will be better if u upload the anaconda environment.yml file -thanks

**Comment by alexstaravoitau** [comment]
Sorry @shahidul56, I worked on this a while back, and have updated most of the dependencies used in that project since then — not sure I will be able to restore which exact versions I used. Sorry about that, I should have thought of it when publishing I suppose!
