### ISSUE TITLE
Cannot run drive.py

### ISSUE THREAD

**Issue by LeenaShekhar** [navoshta/behavioral-cloning#5]
Hi, thank you for the code. I have the following issue:

Command used: 
python drive.py model.json 

Error:
Using Theano backend.
Can not use cuDNN on context None: Disabled by dnn.enabled flag
Mapped name None to device cuda: GeForce GTX TITAN X (0000:01:00.0)
(13106) wsgi starting up on http://0.0.0.0:4567
(13106) accepted ('127.0.0.1', 53040)
127.0.0.1 - - [06/Sep/2018 15:54:56] "GET / HTTP/1.1" 404 366 0.006205

Only change I made is in my theanorc file to disable the dnn flag. 

Please let me know how exactly to run this code.

**Comment by alexstaravoitau** [comment]
Seems like the issue has been resolved now; @LeenaShekhar feel free to provide your solution in comments.
